#!/bin/bash
#

configFile='dotfiles.conf'

# get the items in the config file that aren't commented out
#   ie, the lines that don't begin with a hash symbol (#)
dotfilesToLink=$(egrep '^[^#]' $configFile)

# loop through the dotfiles that we want to link
for currentDotfile in $dotfilesToLink; do
    # init

    # backup old file

    # link

    # initialize
done
