#!/bin/bash
#

configFile='dotfiles.conf'

# date and time, in a parsable format
datetime=$(date '+%Y%m%d%H%M%S')

# get the path to this script
dotfilesRootPath=$(cd $(dirname $0); pwd -P)

# get the items in the config file that aren't commented out
#   ie, the lines that don't begin with a pound/hash symbol (#)
configItemsToProcess=$(egrep '^[^#]' $configFile)

# loop through the dotfiles that we want to link
for currentConfigItem in $configItemsToProcess; do
  echo "processing $currentConfigItem"

  # determine the names of things
  sourcePath=$dotfilesRootPath/$currentConfigItem
  dotfileName=$(basename $sourcePath)
  destPath=$HOME/.$dotfileName

  # initialize

  # link
  # backup old file
  #   if a link.sh script is available, it is responsible for handling backsups
  # if the destination file already exists
  if [[ -e $destPath ]]; then 
    # if already linked to the dotfile
    if [[ $(readlink -f $destPath) != $sourcePath ]]; then 
      # create the name for the backup directory
      backupPath=$dotfilesRootPath/backup/$datetime

      # create the backup dir
      mkdir -p $backupPath
    fi
    echo "$destPath already exists"
  fi
done
